server:
  port: 80
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/lgmall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: "5201314hyq"
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
  elasticsearch:
    rest:
      uris: http://localhost:9200
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com/scorpion/entity
